/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef tutorial_CONSTANTS_H
#define tutorial_CONSTANTS_H

#include "tutorial_types.h"

namespace tutorial {

class tutorialConstants {
 public:
  tutorialConstants();

};

extern const tutorialConstants g_tutorial_constants;

} // namespace

#endif
