/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "tutorial_constants.h"

namespace tutorial {

const tutorialConstants g_tutorial_constants;

tutorialConstants::tutorialConstants() {
}

} // namespace

